# Generated by Django 3.2.5 on 2021-08-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsadmin',
            options={'verbose_name': 'Events Admin', 'verbose_name_plural': 'Events Admins'},
        ),
        migrations.AlterModelOptions(
            name='eventsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Events Admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportimplementationadmin',
            options={'verbose_name': 'Export Implementation'},
        ),
        migrations.AlterModelOptions(
            name='exportimplementationadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Export Implementation Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportlawadmin',
            options={'verbose_name': 'Export Law'},
        ),
        migrations.AlterModelOptions(
            name='exportlawadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Export Law Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportpotentialadmin',
            options={'verbose_name': 'Export Potential'},
        ),
        migrations.AlterModelOptions(
            name='exportpotentialadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Export Potential Translation'},
        ),
        migrations.AlterModelOptions(
            name='investmentpotentialadmin',
            options={'verbose_name': 'Investment potential'},
        ),
        migrations.AlterModelOptions(
            name='investmentpotentialadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Investment potential Translation'},
        ),
        migrations.AlterModelOptions(
            name='investorsadmin',
            options={'verbose_name': 'Investors'},
        ),
        migrations.AlterModelOptions(
            name='investorsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Investors Translation'},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategies',
            options={'verbose_name': 'Market entry strategies'},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategiestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Market entry strategies Translation'},
        ),
    ]
