# Generated by Django 3.2.5 on 2021-08-10 10:11

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210809_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCutLinkIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
