# Generated by Django 3.2.5 on 2021-08-02 10:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210802_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_carousel', models.ImageField(null=True, upload_to='images/', verbose_name='Banner Carousel')),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='eventsadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'events admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportimplementationadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exportimplementationadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'export implementation admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportlawadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exportlawadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'export law admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='exportpotentialadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exportpotentialadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'export potential admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='investmentpotentialadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investmentpotentialadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'investment potential admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='investorsadmin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investorsadmintranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'investors admin Translation'},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketentrystrategiestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'market entry strategies Translation'},
        ),
        migrations.AlterModelOptions(
            name='menusettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menusettingstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'menu settings Translation'},
        ),
        migrations.RemoveField(
            model_name='menusettings',
            name='home_page_gif',
        ),
        migrations.AddField(
            model_name='menusettings',
            name='site_background',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Site Background'),
        ),
        migrations.AddField(
            model_name='menusettings',
            name='site_background2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Site Background 2'),
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.banner')),
            ],
            options={
                'verbose_name': 'Banners Translation',
                'db_table': 'blogs_banner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
