# Generated by Django 3.2.5 on 2021-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_shortcutlinkicons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortCutLinkIcons',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon'),
        ),
    ]
