# Generated by Django 3.2.5 on 2021-08-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210810_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='icons',
            new_name='icon',
        ),
    ]
